#pragma once

#define NOMINMAX
#include <algorithm>
#include <array>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <limits>
#include <memory>
#include <stdexcept>
#include <vector>
#include <glm/glm.hpp>

#define VULKAN_HPP_NO_CONSTRUCTORS
#if defined(__INTELLISENSE__) || !defined(USE_CPP20_MODULES)
#include <vulkan/vulkan_raii.hpp>
#else
import vulkan_hpp;
#endif

#define VK_USE_PLATFORM_WIN32_KHR
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#define GLFW_EXPOSE_NATIVE_WIN32
#include <GLFW/glfw3native.h>

constexpr int MAX_FRAMES_IN_FLIGHT = 2;
constexpr uint32_t SPECTRAL_BINS = 4; // 4-channel Hero Wavelength Sampling

// GPU-aligned data layouts for Wavefront Queues
namespace WavefrontData
{
    // State of a ray traveling through the scene
    struct alignas(16) RayPayload
    {
        glm::vec3 origin;
        float tMin;
        glm::vec3 direction;
        float tMax;

        // Spectral state: sampled wavelengths in nm (e.g. 400nm - 700nm) and PDF weights
        glm::vec4 wavelengths;
        glm::vec4 throughput;

        uint32_t pixelIndex;
        uint32_t bounceCount;
        uint32_t isTerminated; // 1 = terminated, 0 = active
        uint32_t padding;
    };

    // Intersection result generated by the Traversal/Intersect kernel
    struct alignas(16) HitPayload
    {
        glm::vec3 worldPos;
        uint32_t instanceCustomIndex;
        glm::vec3 normal;
        uint32_t primitiveId;
        glm::vec2 uv;
        uint32_t hitStatus; // 0 = miss (environment), 1 = hit
        uint32_t padding;
    };

    // Global push constants / uniform data passed into wavefront stages
    struct SceneParams
    {
        glm::mat4 invView;
        glm::mat4 invProj;
        uint32_t frameCounter;
        uint32_t currentBounce;
        uint32_t maxBounces;
        uint32_t totalPixels;
    };
}

class SpectralWavefrontPt
{
public:
    void run();

private:
    /*---------- WINDOW & CONTEXT ----------*/
    GLFWwindow* window = nullptr;
    const uint32_t WIDTH = 1920;
    const uint32_t HEIGHT = 1080;
    uint32_t frameIndex = 0;

    vk::raii::Context                 context;
    vk::raii::Instance                instance = nullptr;
    vk::raii::DebugUtilsMessengerEXT debugMessenger = nullptr;
    vk::raii::PhysicalDevice         physicalDevice = nullptr;
    vk::raii::Device                 device = nullptr;
    uint32_t                         queueIndex = ~0;
    vk::raii::Queue                  computeAndGraphicsQueue = nullptr;
    vk::raii::SurfaceKHR             surface = nullptr;

    /*---------- SWAPCHAIN ----------*/
    vk::raii::SwapchainKHR           swapChain = nullptr;
    std::vector<vk::Image>           swapChainImages;
    vk::SurfaceFormatKHR             swapChainSurfaceFormat;
    vk::Extent2D                     swapChainExtent;
    std::vector<vk::raii::ImageView> swapChainImageViews;

    /*---------- RAY QUERY & ACCELERATION STRUCTURES ----------*/
    // Bottom Level (Geometry) and Top Level (Scene/Instances)
    vk::raii::AccelerationStructureKHR blas = nullptr;
    vk::raii::Buffer                   blasBuffer = nullptr;
    vk::raii::DeviceMemory             blasMemory = nullptr;
    uint64_t                           blasDeviceAddress = 0;

    vk::raii::AccelerationStructureKHR tlas = nullptr;
    vk::raii::Buffer                   tlasBuffer = nullptr;
    vk::raii::DeviceMemory             tlasMemory = nullptr;
    uint64_t                           tlasDeviceAddress = 0;

    /*---------- WAVEFRONT STORAGE BUFFERS (QUEUES) ----------*/
    // Ray queue ping-pong or active ray buffer
    vk::raii::Buffer                   rayQueueBuffer = nullptr;
    vk::raii::DeviceMemory             rayQueueMemory = nullptr;

    // Hit queue populated by the intersection stage
    vk::raii::Buffer                   hitQueueBuffer = nullptr;
    vk::raii::DeviceMemory             hitQueueMemory = nullptr;

    // Offscreen 32-bit floating point accumulation image (Spectral/XYZ radiance)
    vk::raii::Image                    accumulationImage = nullptr;
    vk::raii::DeviceMemory             accumulationImageMemory = nullptr;
    vk::raii::ImageView                accumulationImageView = nullptr;

    /*---------- DESCRIPTORS ----------*/
    vk::raii::DescriptorSetLayout      descriptorSetLayout = nullptr;
    vk::raii::DescriptorPool           descriptorPool = nullptr;
    vk::raii::DescriptorSets           descriptorSets = nullptr;

    /*---------- COMPUTE PIPELINES (WAVEFRONT PHASES) ----------*/
    vk::raii::PipelineLayout           computePipelineLayout = nullptr;
    vk::raii::Pipeline                 pipelineRayGen = nullptr;       // 1. Generate camera rays & sample wavelengths
    vk::raii::Pipeline                 pipelineIntersect = nullptr;    // 2. Traversal & inline ray queries
    vk::raii::Pipeline                 pipelineShade = nullptr;        // 3. Spectral BSDF sampling & next bounce
    vk::raii::Pipeline                 pipelineTonemap = nullptr;      // 4. XYZ to sRGB conversion & blit

    /*---------- COMMAND BUFFERS & SYNC ----------*/
    vk::raii::CommandPool              commandPool = nullptr;
    std::vector<vk::raii::CommandBuffer> commandBuffers;
    std::vector<vk::raii::Semaphore>   presentCompleteSemaphores;
    std::vector<vk::raii::Semaphore>   renderFinishedSemaphores;
    std::vector<vk::raii::Fence>       inFlightFences;

    /*---------- VALIDATION & EXTENSIONS ----------*/
    const std::vector<const char*> validationLayers = { "VK_LAYER_KHRONOS_validation" };
    const std::vector<const char*> requiredDeviceExtensions = {
        vk::KHRSwapchainExtensionName,
        vk::KHRRayQueryExtensionName,
        vk::KHRAccelerationStructureExtensionName,
        vk::KHRDeferredHostOperationsExtensionName, // Prerequisite for Acceleration Structures
        vk::KHRBufferDeviceAddressExtensionName
    };

#ifdef NDEBUG
    const bool enableValidationLayers = false;
#else
    const bool enableValidationLayers = true;
#endif

    /*---------- CORE SETUP PIPELINE ----------*/
    void initWindow();
    void initVulkan();
    void createInstance();
    std::vector<const char*> getRequiredInstanceExtensions();
    void setupDebugMessenger();
    void createSurface();
    void pickPhysicalDevice();
    bool isDeviceSuitable(const vk::raii::PhysicalDevice& pDevice);
    void createLogicalDevice();
    void createSwapChain();
    void createImageViews();

    /*---------- WAVEFRONT & RAY QUERY INITIALIZATION ----------*/
    void createWavefrontQueues();
    void createAccumulationImage();
    void createAccelerationStructuresPlaceholder();
    void createDescriptorSetLayout();
    void createDescriptorPoolAndSets();
    void createComputePipelines();

    /*---------- RUNTIME ----------*/
    void createCommandPool();
    void createCommandBuffers();
    void createSyncObjects();
    void recordWavefrontCommands(uint32_t imageIndex);
    void drawFrame();
    void mainLoop();
    void cleanup();
    void recreateSwapChain();
    void cleanupSwapChain();

    /*---------- UTILITIES ----------*/
    uint32_t findMemoryType(uint32_t typeFilter, vk::MemoryPropertyFlags properties);
    static std::vector<char> readFile(const std::string& filename);
    [[nodiscard]] vk::raii::ShaderModule createShaderModule(const std::vector<char>& code) const;
    static VKAPI_ATTR vk::Bool32 VKAPI_CALL debugCallback(
        vk::DebugUtilsMessageSeverityFlagBitsEXT severity,
        vk::DebugUtilsMessageTypeFlagsEXT type,
        const vk::DebugUtilsMessengerCallbackDataEXT* pCallbackData,
        void*);
};