#pragma once

#define NOMINMAX
#include <algorithm>
#include <array>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <limits>
#include <memory>
#include <stdexcept>
#include <vector>
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>



#define VULKAN_HPP_NO_CONSTRUCTORS
#if defined(__INTELLISENSE__) || !defined(USE_CPP20_MODULES)
#include <vulkan/vulkan_raii.hpp>
#else
import vulkan_hpp;
#endif

#define VK_USE_PLATFORM_WIN32_KHR
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#define GLFW_EXPOSE_NATIVE_WIN32
#include <GLFW/glfw3native.h>

constexpr int MAX_FRAMES_IN_FLIGHT = 2;
constexpr uint32_t SPECTRAL_BINS = 4; // 4-channel Hero Wavelength Sampling

// GPU-aligned data layouts for Wavefront Queues
namespace WavefrontData
{
    // State of a ray traveling through the scene
    struct alignas(16) RayPayload
    {
        glm::vec3 origin;
        float tMin;
        glm::vec3 direction;
        float tMax;

        // Spectral state: sampled wavelengths in nm (e.g. 400nm - 700nm) and PDF weights
        glm::vec4 wavelengths;
        glm::vec4 throughput;

        uint32_t pixelIndex;
        uint32_t bounceCount;
        uint32_t isTerminated; // 1 = terminated, 0 = active
        uint32_t padding;
    };

    // Intersection result generated by the Traversal/Intersect kernel
    struct alignas(16) HitPayload
    {
        glm::vec3 worldPos;
        uint32_t instanceCustomIndex;
        glm::vec3 normal;
        uint32_t primitiveId;
        glm::vec2 uv;
        uint32_t hitStatus; // 0 = miss (environment), 1 = hit
        uint32_t padding;
    };

    // Global push constants / uniform data passed into wavefront stages
    struct SceneParams
    {
        glm::mat4 invView;
        glm::mat4 invProj;

        uint64_t  vertexBufferAddress;
        uint64_t  indexBufferAddress;

        glm::vec2 shiftOffset{ 0.0f, 0.0f };
        glm::vec2 tiltAxis{ 0.0f, 1.0f };

        float     tiltAngle{ 0.0f };
        float     focalDistance{ 5.0f };
        float     apertureRadius{ 0.0f };
        uint32_t  width{ 1920 };

        uint32_t  height{ 1080 };
        uint32_t  frameCounter{ 0 };
        uint32_t  currentBounce{ 0 };
        uint32_t  maxBounces{ 8 };

        uint32_t  totalPixels{ 1920 * 1080 };
        uint32_t  pad0{ 0 };
        uint32_t  pad1{ 0 };
        uint32_t  pad2{ 0 };
    };

    struct alignas(16) GpuMeshDesc {
        uint64_t positionBufferAddress;
        uint64_t attributtesBufferAddress;
        uint64_t indexBufferAddress;
        uint32_t materialId;
        uint32_t padding;
    };
}

struct VertexAttributes
{
    glm::vec3 norm;
    glm::vec2 uv;
};

struct Camera {
    glm::vec3 position;
    glm::vec3 target;
    glm::vec3 up{ 0.0f, 1.0f, 0.0f };
    float fovY{ 45.0f }; // vertical field of view in degrees
};

struct MeshGeometry {
    std::vector<glm::vec3> vertices;
    std::vector<VertexAttributes> attributes;
    std::vector<uint32_t> indices;

    // Per-mesh GPU allocations
    vk::raii::Buffer vertexBuffer = nullptr;
    vk::raii::DeviceMemory vertexBufferMemory = nullptr;
    vk::raii::Buffer attributeBuffer = nullptr;
    vk::raii::DeviceMemory attributeBufferMemory = nullptr;
    vk::raii::Buffer indexBuffer = nullptr;
    vk::raii::DeviceMemory indexBufferMemory = nullptr;

    vk::raii::Buffer blasBuffer = nullptr;
    vk::raii::DeviceMemory blasMemory = nullptr;
    vk::raii::AccelerationStructureKHR blas = nullptr;
    vk::DeviceAddress blasAddress = 0;
};

struct SceneInstance {
    uint32_t meshIndex{ 0 };
    glm::mat4 transform{ 1.0f };
    uint32_t customInstanceId{ 0 };
    uint32_t materialId{ 0 };
};


class SpectralWavefrontPt
{
public:
    void run();

private:
    /*---------- WINDOW & CONTEXT ----------*/
    GLFWwindow* window = nullptr;
    const uint32_t WIDTH = 1920;
    const uint32_t HEIGHT = 1080;
    uint32_t frameIndex = 0;

    vk::raii::Context                 context;
    vk::raii::Instance                instance = nullptr;
    vk::raii::DebugUtilsMessengerEXT debugMessenger = nullptr;
    vk::raii::PhysicalDevice         physicalDevice = nullptr;
    vk::raii::Device                 device = nullptr;
    uint32_t                         queueIndex = ~0;
    vk::raii::Queue                  computeAndGraphicsQueue = nullptr;
    vk::raii::SurfaceKHR             surface = nullptr;

    /*---------- SWAPCHAIN ----------*/
    vk::raii::SwapchainKHR           swapChain = nullptr;
    std::vector<vk::Image>           swapChainImages;
    vk::SurfaceFormatKHR             swapChainSurfaceFormat;
    vk::Extent2D                     swapChainExtent;
    std::vector<vk::raii::ImageView> swapChainImageViews;

    /*---------- SCENE GEOMETRY & ACCELERATION STRUCTURES ----------*/
    // Bottom Level (Meshes/Instances) and Top Level (Scene/Instances)
    Camera                              camera;
    glm::mat4                           invView{ 1.0f };
    glm::mat4                           invProj{ 1.0f };

    std::vector<MeshGeometry>           meshes;
    std::vector<SceneInstance>          instances;
    vk::raii::AccelerationStructureKHR  tlas = nullptr;
    vk::raii::Buffer                   tlasBuffer = nullptr;
    vk::raii::DeviceMemory             tlasMemory = nullptr;
    uint64_t                           tlasDeviceAddress = 0;

    vk::raii::Buffer                   meshDescBuffer = nullptr;
    vk::raii::DeviceMemory             meshDescMemory = nullptr;
    uint64_t                           meshDescAddress = 0;


    /*---------- WAVEFRONT STORAGE BUFFERS (QUEUES) ----------*/
    // Ray queue ping-pong or active ray buffer
    vk::raii::Buffer                   rayQueueBuffer = nullptr;
    vk::raii::DeviceMemory             rayQueueMemory = nullptr;

    // Hit queue populated by the intersection stage
    vk::raii::Buffer                   hitQueueBuffer = nullptr;
    vk::raii::DeviceMemory             hitQueueMemory = nullptr;

    // Offscreen 32-bit floating point accumulation image (Spectral/XYZ radiance)
    vk::raii::Image                    accumulationImage = nullptr;
    vk::raii::DeviceMemory             accumulationImageMemory = nullptr;
    vk::raii::ImageView                accumulationImageView = nullptr;

    /*---------- DESCRIPTORS ----------*/
    vk::raii::DescriptorSetLayout      descriptorSetLayout = nullptr;
    vk::raii::DescriptorPool           descriptorPool = nullptr;
    vk::raii::DescriptorSets           descriptorSets = nullptr;

    /*---------- COMPUTE PIPELINES (WAVEFRONT PHASES) ----------*/
    vk::raii::PipelineLayout           computePipelineLayout = nullptr;
    vk::raii::Pipeline                 pipelineRayGen = nullptr;       // 1. Generate camera rays & sample wavelengths
    vk::raii::Pipeline                 pipelineIntersect = nullptr;    // 2. Traversal & inline ray queries
    vk::raii::Pipeline                 pipelineShade = nullptr;        // 3. Spectral BSDF sampling & next bounce
    vk::raii::Pipeline                 pipelineTonemap = nullptr;      // 4. XYZ to sRGB conversion & blit

    /*---------- COMMAND BUFFERS & SYNC ----------*/
    vk::raii::CommandPool              commandPool = nullptr;
    std::vector<vk::raii::CommandBuffer> commandBuffers;
    std::vector<vk::raii::Semaphore>   presentCompleteSemaphores;
    std::vector<vk::raii::Semaphore>   renderFinishedSemaphores;
    std::vector<vk::raii::Fence>       inFlightFences;

    /*---------- VALIDATION & EXTENSIONS ----------*/
    const std::vector<const char*> validationLayers = { "VK_LAYER_KHRONOS_validation" };
    const std::vector<const char*> requiredDeviceExtensions = {
        vk::KHRSwapchainExtensionName,
        vk::KHRRayQueryExtensionName,
        vk::KHRAccelerationStructureExtensionName,
        vk::KHRDeferredHostOperationsExtensionName, 
        vk::KHRBufferDeviceAddressExtensionName
    };

#ifdef NDEBUG
    const bool enableValidationLayers = false;
#else
    const bool enableValidationLayers = true;
#endif

    /*---------- CORE SETUP PIPELINE ----------*/
    void initWindow();
    void initVulkan();
    void createInstance();
    std::vector<const char*> getRequiredInstanceExtensions();
    void setupDebugMessenger();
    void createSurface();
    void pickPhysicalDevice();
    bool isDeviceSuitable(const vk::raii::PhysicalDevice& pDevice);
    void createLogicalDevice();
    void createSwapChain();
    void createImageViews();

    /*---------- WAVEFRONT & RAY QUERY INITIALIZATION ----------*/
    void createWavefrontQueues();
    void createAccumulationImage();
    void createDescriptorSetLayout();
    void createDescriptorPoolAndSets();
    void createComputePipelines();

    /*---------- SCENE, OBJECT, ACCELERATION STRUCTURE CREATION ----------*/

    /*---------- SCENE, OBJECT, ACCELERATION STRUCTURE CREATION ----------*/
    void createScene();
    void createAccelerationStructures();
    void buildBLAS(MeshGeometry& mesh);
    void buildTLAS();
    void buildAccelerationStructureOnGPU
    (
        vk::AccelerationStructureBuildGeometryInfoKHR buildInfo,
        vk::AccelerationStructureKHR as,
        vk::DeviceSize scratchSize,
        uint32_t primitiveCount
    );
    void createMeshDescriptorBuffer();

    /*---------- RUNTIME ----------*/
    void createCommandPool();
    void createCommandBuffers();
    void createSyncObjects();
    void recordWavefrontCommands(uint32_t imageIndex);
    void drawFrame();
    void mainLoop();
    void cleanup();
    void recreateSwapChain();
    void cleanupSwapChain();

    /*---------- UTILITIES ----------*/
    uint32_t findMemoryType(uint32_t typeFilter, vk::MemoryPropertyFlags properties);
    static std::vector<char> readFile(const std::string& filename);
    [[nodiscard]] vk::raii::ShaderModule createShaderModule(const std::vector<char>& code) const;
    static VKAPI_ATTR vk::Bool32 VKAPI_CALL debugCallback(
        vk::DebugUtilsMessageSeverityFlagBitsEXT severity,
        vk::DebugUtilsMessageTypeFlagsEXT type,
        const vk::DebugUtilsMessengerCallbackDataEXT* pCallbackData,
        void*);
};